// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./../src/components/home/index.vue')['default']
    HomeTopNav: typeof import('./../src/components/home/TopNav.vue')['default']
    HomeTopNavItem: typeof import('./../src/components/home/TopNavItem.vue')['default']
    HomeTopNavList: typeof import('./../src/components/home/TopNavList.vue')['default']
    IconList: typeof import('./../src/components/IconList/index.vue')['default']
    IocoList: typeof import('./../src/components/IocoList/index.vue')['default']
    Item: typeof import('./../src/components/Item.vue')['default']
    LocoList: typeof import('./../src/components/LocoList/index.vue')['default']
    MusicList: typeof import('./../src/components/MusicList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./../src/components/swiper/index.vue')['default']
    TopNav: typeof import('./../src/components/TopNav/index.vue')['default']
    TopNavItem: typeof import('./../src/components/TopNav/Item.vue')['default']
    TopNavTopNavItem: typeof import('./../src/components/TopNav/TopNavItem.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
